# Generated by Django 5.2.13 on 2026-05-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_premiumrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='₺', max_length=10)),
                ('period', models.CharField(max_length=20)),
                ('icon', models.CharField(default='⚡', max_length=10)),
                ('features', models.TextField(help_text='One feature per line')),
                ('has_priority_support', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('promo_text', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='plan',
            field=models.CharField(choices=[('weekly', 'Weekly - 49TL'), ('monthly', 'Monthly - 149TL'), ('yearly', 'Yearly - 999TL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='premiumrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
