# Generated by Django 5.2.13 on 2026-05-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pricingplan_alter_premiumrequest_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='educator_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_educator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EducatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educator_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
