# Generated by Django 5.2.13 on 2026-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studyroom_is_premium_room_tutorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
