# Generated by Django 5.2.13 on 2026-05-10 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sharedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('note', 'Course Note'), ('video', 'Video Resource')], default='note', max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_students', models.IntegerField(default=2)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('allow_camera', models.BooleanField(default=True)),
                ('allow_mic', models.BooleanField(default=True)),
                ('allow_chat', models.BooleanField(default=True)),
                ('allow_notes', models.BooleanField(default=True)),
                ('allow_files', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invite_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
