# Generated by Django 5.2.13 on 2026-05-10 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('join_request', 'Join Request'), ('join_accepted', 'Join Accepted'), ('join_rejected', 'Join Rejected')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
