# Generated by Django 5.2.13 on 2026-05-10 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_directmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kicked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kicks_given', to=settings.AUTH_USER_MODEL)),
                ('kicked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kicks_received', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kick_logs', to='core.studyroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
