from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('rooms/', views.room_list, name='rooms'),
    path('create-room/', views.create_room, name='create-room'),

    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('register/', views.register, name='register'),
    path('room/<int:pk>/', views.room_detail, name='room-detail'),
    path('save-notes/<int:pk>/', views.save_notes, name='save-notes'),
    path('room/<int:room_pk>/kick/<int:user_pk>/', views.kick_participant, name='kick-participant'),
    path('room/<int:room_pk>/check-kick/', views.check_kick, name='check-kick'),
    path('room/<int:pk>/delete/', views.delete_room, name='delete-room'),
    path('room/<int:room_pk>/delete-message/<int:msg_pk>/', views.delete_message, name='delete-message'),
    path('room/<int:room_pk>/ai/', views.ai_assistant, name='ai-assistant'),
    path('room/<int:room_pk>/media-control/', views.media_control, name='media-control'),
    path('room/<int:room_pk>/check-media/', views.check_media_control, name='check-media-control'),
    path('room/<int:room_pk>/upload/', views.upload_file, name='upload-file'),
    path('room/<int:room_pk>/file/<int:file_pk>/delete/', views.delete_file, name='delete-file'),
    path('tutor-requests/post/', views.post_tutor_request, name='post-tutor-request'),
    path('tutor-requests/list/', views.get_tutor_requests, name='get-tutor-requests'),
    path('room/<int:pk>/edit/', views.edit_room, name='edit-room'),
    path('documentation/', views.documentation, name='documentation'),
    path('documentation/create/', views.create_doc_content, name='create-doc-content'),
    path('documentation/delete/<int:content_pk>/', views.delete_doc_content, name='delete-doc-content'),
    path('lesson-rooms/', views.lesson_rooms, name='lesson-rooms'),
    path('lesson-rooms/create/', views.create_lesson_room, name='create-lesson-room'),
    path('lesson-rooms/<int:room_pk>/edit/', views.edit_lesson_room, name='edit-lesson-room'),
    path('lesson-rooms/<int:room_pk>/delete/', views.delete_lesson_room, name='delete-lesson-room'),
    path('lesson-rooms/<int:room_pk>/', views.lesson_room_detail, name='lesson-room-detail'),
    path('lesson-rooms/<int:room_pk>/kick/<int:user_pk>/', views.kick_lesson_participant, name='kick-lesson-participant'),
    path('lesson-rooms/<int:room_pk>/participants/', views.lesson_participants, name='lesson-participants'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/read/', views.mark_notifications_read, name='notifications-read'),
    path('notifications/send-to-educator/', views.send_to_educator, name='send-to-educator'),
    path('dm/users/', views.dm_users, name='dm-users'),
    path('dm/messages/<int:user_id>/', views.dm_messages, name='dm-messages'),
    path('dm/send/', views.dm_send, name='dm-send'),
    path('dm/unread/', views.dm_unread_count, name='dm-unread'),
    path('notifications/respond/', views.respond_join_request, name='respond-join-request'),
    path('verify-yeditepe/', views.yeditepe_verify, name='yeditepe-verify'),
    path('verify-yeditepe/approve/<int:verify_id>/', views.yeditepe_approve, name='yeditepe-approve'),
    path('verify-yeditepe/reject/<int:verify_id>/', views.yeditepe_reject, name='yeditepe-reject'),
    path('premium/', views.pricing, name='pricing'),
    path('premium/edit/<str:plan_key>/', views.edit_plan, name='edit_plan'),
    path('premium-rooms/', views.lesson_rooms, name='lesson-rooms'),
    path('premium-rooms/', views.lesson_rooms, name='premium-rooms'),
    path('premium-rooms/<str:room_id>/', views.premium_room_detail, name='premium-room-detail'),
    path('premium/request/', views.premium_request, name='premium_request'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/approve/<int:req_id>/', views.approve_premium, name='approve_premium'),
    path('admin-panel/reject/<int:req_id>/', views.reject_premium, name='reject_premium'),
    path('educator/request/', views.request_educator, name='request_educator'),
    path('educator/approve/<int:req_id>/', views.approve_educator, name='approve_educator'),
    path('educator/reject/<int:req_id>/', views.reject_educator, name='reject_educator'),
    path('premium-rooms/<str:room_id>/enter/', views.enter_premium_room, name='enter-premium-room'),
]